src/objects/AsyncRequest__c.object
<CustomObject>
    <fields>
        <fullName>Aborted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Signifies this async request job has been aborted due to too many failed attempts</description>
        <inlineHelpText>Signifies this async request job has been aborted due to too many failed attempts</inlineHelpText>
        <label>Aborted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AsyncType__c</fullName>
        <label>AsyncType</label>
        <picklist>
            <picklistValues>
                <fullName>Default</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Attempts__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of times this async request has been attempted</description>
        <inlineHelpText>Number of times this async request has been attempted</inlineHelpText>
        <label>Attempts</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JobId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Id of the Queueable Apex job associated with this async request, if any</description>
        <externalId>true</externalId>
        <inlineHelpText>Id of the Queueable Apex job associated with this async request, if any</inlineHelpText>
        <label>Job Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MaxAttempts__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Determines the maximum number of times this async request should run before it is aborted</description>
        <inlineHelpText>Determines the maximum number of times this async request should run before it is aborted</inlineHelpText>
        <label>Max Attempts</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Params__c</fullName>
        <label>Params</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>AsyncRequest</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>AsyncRequest</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AsyncRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RepeatingFuture.cls
/**
* @author Scott Covert
* @date 5/14/2015
* @description Defines the Future Handler for Scheduler Ping-Pong.
*/
public class RepeatingFuture {
    /** Constant representing the token that forces repeating future calls in lieu of Batch Apex */
    private static final String FUTURE_TOKEN = ScheduleHandler.FUTURE_TOKEN;
    /** Constant representing default ASyncRequest type */
    public static final String TYPE_DEFAULT = ScheduleHandler.FUTURE_TOKEN + 'Default';

    /**
    * @author Scott Covert
    * @date 5/14/2015
    * @description Attempts to execute Future AsyncRequests.
    */    
    public static void Start(){
        List<AsyncRequest__c> arsToDelete = new List<AsyncRequest__c>();
        String futureType = FUTURE_TOKEN + '%';
        for (AsyncRequest__c ar : [SELECT Id, AsyncType__c, JobId__c, ScheduledTime__c, Params__c, Attempts__c, MaxAttempts__c, Aborted__c FROM AsyncRequest__c WHERE Aborted__c = false AND AsyncType__c LIKE :futureType ORDER BY ScheduledTime__c ASC LIMIT 1]){
            if (ar.AsyncType__c == TYPE_DEFAULT){
                if (ar.Params__c!=null){
                    List<Id> idsToProcess = ar.Params__c.split(',');
                    System.debug('This is an example of calling an asynchronous method with a list of ids to be processed...');
                }
                arsToDelete.add(ar);
            }
        }
        if (arsToDelete.size()>0){
            // Delete AsyncRequests
            DMLManager.deleteAsSystem(arsToDelete);
            Database.emptyRecycleBin(arsToDelete);
        }
        ScheduleHandler.StartScheduler();
    }
}