src/objects/AsyncRequest__c.object
<CustomObject>
    <fields>
        <fullName>AsyncType__c</fullName>
        <label>AsyncType</label>
        <picklist>
            <picklistValues>
                <fullName>Default</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Params__c</fullName>
        <label>Params</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Scheduled_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Scheduled Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>AsyncRequest</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>AsyncRequest</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AsyncRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RepeatingBatch.cls
/**
* @author Scott Covert
* @date 1/16/2015
* @description Defines the Batch Apex for Scheduler Ping-Pong.
*/
public class RepeatingBatch implements Database.Batchable<sObject> {
    /**
	* @author Scott Covert
	* @date 1/16/2015
	* @description Defines the QueryLocator to retrieve any AsyncRequests at or past their scheduled time.
	*/
    public Database.QueryLocator start(Database.BatchableContext BC){
        DateTime now = System.now();
        return Database.getQueryLocator('SELECT Id, AsyncType__c, Scheduled_Time__c, Params__c FROM AsyncRequest__c WHERE Scheduled_Time__c <= :now');
    }
    
    /**
	* @author Scott Covert
	* @date 1/16/2015
	* @description Attempts to execute AsyncRequests.
	*/    
    public void execute(Database.BatchableContext BC, List<AsyncRequest__c> scope){
        try{
        	System.debug('This is an example of calling synchronous code from asynchronous process...');
        	// Delete AsyncRequests
        	delete scope;
        	Database.emptyRecycleBin(scope);
        }
        catch(Exception e){
        	// Error -> Preserve AsyncRequests
        }
        delete scope;
    }

    /**
	* @author Scott Covert
	* @date 1/16/2015
	* @description Execute Scheduled Apex for Scheduler Ping-Pong.
	*/  
    public void finish(Database.BatchableContext BC){
    	ScheduleHandler.StartScheduler();
    }
    
    /**
	* @author Scott Covert
	* @date 1/16/2015
	* @description Execute Batch Apex for Scheduler Ping-Pong with a batch size of one.
	*/  
    public static void StartTheBatch()
    {
        RepeatingBatch rb = new RepeatingBatch();
        Database.executeBatch(rb, 1);
    }
}