src/objects/AsyncRequest__c.object
<CustomObject>
    <fields>
        <fullName>Aborted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Signifies this async request job has been aborted due to too many failed attempts</description>
        <inlineHelpText>Signifies this async request job has been aborted due to too many failed attempts</inlineHelpText>
        <label>Aborted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AsyncType__c</fullName>
        <label>AsyncType</label>
        <picklist>
            <picklistValues>
                <fullName>Default</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Attempts__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of times this async request has been attempted</description>
        <inlineHelpText>Number of times this async request has been attempted</inlineHelpText>
        <label>Attempts</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JobId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Id of the Queueable Apex job associated with this async request, if any</description>
        <externalId>true</externalId>
        <inlineHelpText>Id of the Queueable Apex job associated with this async request, if any</inlineHelpText>
        <label>Job Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MaxAttempts__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Determines the maximum number of times this async request should run before it is aborted</description>
        <inlineHelpText>Determines the maximum number of times this async request should run before it is aborted</inlineHelpText>
        <label>Max Attempts</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Params__c</fullName>
        <label>Params</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Scheduled_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Scheduled Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>AsyncRequest</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>AsyncRequest</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AsyncRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CalloutRequest__c.object
<CustomObject>
    <description>Callout requests made on behalf of the application</description>
    <fields>
        <fullName>Endpoint__c</fullName>
        <description>Endpoint URL of external server&apos;s API</description>
        <inlineHelpText>Endpoint URL of external server&apos;s API</inlineHelpText>
        <label>Endpoint</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JobId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Id of the Queueable Apex job associated with this callout, if any</description>
        <externalId>true</externalId>
        <inlineHelpText>Id of the Queueable Apex job associated with this callout, if any</inlineHelpText>
        <label>Job Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <description>HTTP Method to be used for the callout (GET, POST, etc.)</description>
        <inlineHelpText>HTTP Method to be used for the callout (GET, POST, etc.)</inlineHelpText>
        <label>Method</label>
        <picklist>
            <picklistValues>
                <fullName>GET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>POST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PUT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PATCH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DELETE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sent__c</fullName>
        <description>Timestamp of when the callout was sent</description>
        <inlineHelpText>Timestamp of when the callout was sent</inlineHelpText>
        <label>Sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Timeout__c</fullName>
        <description>Timeout for the callout in seconds</description>
        <inlineHelpText>Timeout for the callout in seconds</inlineHelpText>
        <label>Timeout</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Callout Request</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Callout Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callout Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QueueableHandler.cls
/**
* @author Scott Covert
* @date 2/21/2016
* @description Defines the Handler for Queueable Apex
*/
public class QueueableHandler implements QueueableDispatcher.IQueueableDispatched {
	/** Constant representing the token that signifies the queueable apex is to perform a callout */
	public static final String CALLOUT_TOKEN = 'Callout:';

	/**
	* @author Scott Covert
	* @date 2/21/2016
	* @description Execute Queueable Apex
	* @param QueueableContext Current schedulable context
	*/
	public void execute(QueueableContext sc)
    {
    	List<AsyncRequest__c> asyncRequests = [SELECT Id, AsyncType__c, JobId__c, Scheduled_Time__c, Params__c, Attempts__c, Aborted__c FROM AsyncRequest__c WHERE Aborted__c = false ORDER BY Scheduled_Time__c ASC LIMIT 1];
    	// End chaining if all asynchronous requests have been processed
        if (asyncRequests.size() == 0) return;
        AsyncRequest__c ar = asyncRequests[0];
        Map<Id,AsyncRequest__c> arsToDelete = new Map<Id,AsyncRequest__c>();
    	try{
    		if (ar.AsyncType__c.contains(CALLOUT_TOKEN)){
	        	// Initialize Callout Handler
	        	List<CalloutRequest__c> calloutRequests = [SELECT Id, JobId__c, Endpoint__c, Method__c, Timeout__c, Status__c, Sent__c, Request__c, Response__c FROM CalloutRequest__c WHERE JobId__c = :ar.JobId__c LIMIT 1];
	        	if (calloutRequests.size()!=0) CalloutHandler.Start(calloutRequests[0]);
	        	arsToDelete.put(ar.Id,ar);
	        }
    	}
    	catch(Exception e){
    		// Error -> Preserving AsyncRequest leaves the job at the beginning of the queue
    		DiagnosticsInstrumentation.DebugException(e);
            DiagnosticsInstrumentation.PopAll();
        }

        // Increment attempts counter
		ar.Attempts__c++;
		if (ar.Attempts__c >= ar.MaxAttempts__c)
		{
			// This async request has failed the maximum number of times allowed; abort
			ar.Aborted__c = true;
		}
		// Only bother to update async request if it is not set to be deleted
        if (!arsToDelete.containsKey(ar.Id)) update ar;				
        if (!arsToDelete.isEmpty())
        {
            // Delete executed AsyncRequests
            delete arsToDelete.values();
            Database.emptyRecycleBin(arsToDelete.values());
        }
        // Chain job to process additional async requests
        chainJob();
    }

    /**
    * @author Scott Covert - Tython Co.
    * @date 2/22/2016
    * @description Chains Queueable Apex
    */
    @future
    private static void chainJob()
    {
        System.enqueueJob(new QueueableDispatcher());
    }

}