src/objects/AsyncRequest__c.object
<CustomObject>
    <fields>
        <fullName>Aborted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Signifies this async request job has been aborted due to too many failed attempts</description>
        <inlineHelpText>Signifies this async request job has been aborted due to too many failed attempts</inlineHelpText>
        <label>Aborted</label>
        <type>Checkbox</type>
    </fields>
    <label>AsyncRequest</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>AsyncRequest</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AsyncRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CalloutRequest__c.object
<CustomObject>
    <description>Callout requests made on behalf of the application</description>
    <fields>
        <fullName>Endpoint__c</fullName>
        <description>Endpoint URL of external server&apos;s API</description>
        <inlineHelpText>Endpoint URL of external server&apos;s API</inlineHelpText>
        <label>Endpoint</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <description>HTTP Method to be used for the callout (GET, POST, etc.)</description>
        <inlineHelpText>HTTP Method to be used for the callout (GET, POST, etc.)</inlineHelpText>
        <label>Method</label>
        <picklist>
            <picklistValues>
                <fullName>GET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>POST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PUT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PATCH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DELETE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Timeout__c</fullName>
        <description>Timeout for the callout in seconds</description>
        <inlineHelpText>Timeout for the callout in seconds</inlineHelpText>
        <label>Timeout</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Callout Request</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Callout Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callout Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QueueableHandlerTest.cls
/**
* @author Scott Covert
* @date 6/17/2016
* @description This class provides unit tests for the QueueableHandler test class
*/
@isTest (seealldata=false)
public with sharing class QueueableHandlerTest { 

	/** Constant representing endpoint of external API for testing */
	private static final String TEST_ENDPOINT = 'https://httpbin.org/get';

	/** 
	* @author Scott Covert
	* @date 6/17/2016
	* @description Tests the QueueableHandler methods
	*/
	@isTest (seealldata=false)
	public static void testQueueableHandler() {	        
        
	if (!TestVerificationService.ShouldExecute('QueueableHandlerTest.testQueueableHandler')) return;

        // Test Async Request Queue is functional
        QueueableHandler.startCalloutJob(QueueableHandler.CALLOUT_TOKEN, new CalloutRequest__c(Endpoint__c = TEST_ENDPOINT, Method__c = CalloutHandler.GET_METHOD, Timeout__c = CalloutHandler.DEFAULT_CALLOUT_TIME));
		list<AsyncRequest__c> asyncRequests = [SELECT Id FROM AsyncRequest__c WHERE Aborted__c = false];
		System.assertNotEquals(asyncRequests.size(),0,'Error in QueueableHandler.startJob: Async Request record(s) not being properly inserted to the database/queue');		

	}

}